/*
 * Peer.java
 *
 * Created on __DATE__, __TIME__
 */

package com.design;

import java.io.File;
import java.util.Vector;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;

import com.ctrl.Action;
import com.ctrl.Receive;
import com.multicast.MulticastRx;
import com.multicast.MulticastTx;

/**
 * 
 * @author __USER__
 */
public class Server extends javax.swing.JFrame {

	/** Creates new form Peer */
	private static final long serialVersionUID = 1L;
	public Action action;
	public String source;
	int port;
	public String dis;
	public MulticastRx mrx;
	Receive receive;
	String mpcrPath;

	public Server() {
		initComponents();
		init();
	}

	private void init() {
		// TODO Auto-generated method stub
		allFiles = new Vector<String>();
		action = new Action();
		source = action.getSource();
		setTitle(source);
		txtNme.setText(source);
		port = action.getPort();
		txtPort.setText("" + port);
		receive = new Receive(this, port, action);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jtaNeigh = new javax.swing.JTextArea();
		jLabel6 = new javax.swing.JLabel();
		txtDistance = new javax.swing.JTextField();
		btnMRWB = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		txtNme = new javax.swing.JTextField();
		jScrollPane2 = new javax.swing.JScrollPane();
		tblAData = new javax.swing.JTable();
		jLabel3 = new javax.swing.JLabel();
		btnAdd = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();
		txtPort = new javax.swing.JTextField();
		jPanel3 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		txtSearch = new javax.swing.JTextField();
		btnSearch = new javax.swing.JButton();
		jScrollPane3 = new javax.swing.JScrollPane();
		jtaSarchDet = new javax.swing.JTextArea();
		jLabel7 = new javax.swing.JLabel();
		btnDown = new javax.swing.JButton();
		jScrollPane4 = new javax.swing.JScrollPane();
		tblDown = new javax.swing.JTable();
		jPanel4 = new javax.swing.JPanel();
		jScrollPane5 = new javax.swing.JScrollPane();
		tblDataTx = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		getContentPane().setLayout(null);

		jLabel1.setFont(new java.awt.Font("Britannic Bold", 1, 18));
		jLabel1.setForeground(new java.awt.Color(153, 0, 204));
		jLabel1.setText("Load Balancing Control of Server Clusters");
		getContentPane().add(jLabel1);
		jLabel1.setBounds(70, 0, 530, 30);

		jPanel1.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Available Servers"));
		jPanel1.setLayout(null);

		jtaNeigh.setColumns(20);
		jtaNeigh.setRows(5);
		jScrollPane1.setViewportView(jtaNeigh);

		jPanel1.add(jScrollPane1);
		jScrollPane1.setBounds(10, 40, 220, 100);

		jLabel6.setText("Tasks :");
		jPanel1.add(jLabel6);
		jLabel6.setBounds(10, 16, 50, 20);
		jPanel1.add(txtDistance);
		txtDistance.setBounds(70, 17, 65, 20);

		btnMRWB.setText("CTCT");
		btnMRWB.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnMRWBActionPerformed(evt);
			}
		});
		jPanel1.add(btnMRWB);
		btnMRWB.setBounds(140, 16, 90, 23);

		getContentPane().add(jPanel1);
		jPanel1.setBounds(10, 330, 240, 150);

		jPanel2.setBorder(javax.swing.BorderFactory
				.createTitledBorder("ServerDetails"));
		jPanel2.setLayout(null);

		jLabel2.setText("Name :");
		jPanel2.add(jLabel2);
		jLabel2.setBounds(10, 20, 40, 20);
		jPanel2.add(txtNme);
		txtNme.setBounds(50, 20, 60, 20);

		dftFiles = new DefaultTableModel();
		tblAData.setModel(dftFiles);
		jScrollPane2.setViewportView(tblAData);
		dftFiles.addColumn("Data Avilability::");
		jPanel2.add(jScrollPane2);
		jScrollPane2.setBounds(10, 70, 220, 190);

		jLabel3.setText("Available Data :");
		jPanel2.add(jLabel3);
		jLabel3.setBounds(10, 50, 120, 14);

		btnAdd.setText("Add");
		btnAdd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAddActionPerformed(evt);
			}
		});
		jPanel2.add(btnAdd);
		btnAdd.setBounds(60, 266, 120, 23);

		jLabel5.setText("Port :");
		jPanel2.add(jLabel5);
		jLabel5.setBounds(120, 20, 27, 20);
		jPanel2.add(txtPort);
		txtPort.setBounds(150, 20, 70, 20);

		getContentPane().add(jPanel2);
		jPanel2.setBounds(10, 30, 240, 300);

		jPanel3.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Search Details"));
		jPanel3.setLayout(null);

		jLabel4.setText("Enter the File Name:");
		jPanel3.add(jLabel4);
		jLabel4.setBounds(20, 20, 110, 14);
		jPanel3.add(txtSearch);
		txtSearch.setBounds(130, 20, 280, 20);

		btnSearch.setText("Search");
		btnSearch.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSearchActionPerformed(evt);
			}
		});
		jPanel3.add(btnSearch);
		btnSearch.setBounds(130, 50, 110, 23);

		jtaSarchDet.setColumns(20);
		jtaSarchDet.setRows(5);
		jScrollPane3.setViewportView(jtaSarchDet);

		jPanel3.add(jScrollPane3);
		jScrollPane3.setBounds(10, 80, 400, 100);

		jLabel7.setText("Server Details :");
		jPanel3.add(jLabel7);
		jLabel7.setBounds(10, 60, 160, 14);

		btnDown.setText("Load");
		btnDown.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDownActionPerformed(evt);
			}
		});
		jPanel3.add(btnDown);
		btnDown.setBounds(250, 50, 160, 23);

		dftDown = new DefaultTableModel();
		tblDown.setModel(dftDown);
		jScrollPane4.setViewportView(tblDown);
		dftDown.addColumn("Packet");
		dftDown.addColumn("Data");
		dftDown.addColumn("Downloaded Servers");

		jPanel3.add(jScrollPane4);
		jScrollPane4.setBounds(10, 190, 400, 130);

		getContentPane().add(jPanel3);
		jPanel3.setBounds(250, 30, 420, 330);

		jPanel4.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Data Transfer Details"));
		jPanel4.setLayout(null);

		dftDataTx = new DefaultTableModel();
		tblDataTx.setModel(dftDataTx);
		jScrollPane5.setViewportView(tblDataTx);
		dftDataTx.addColumn("Server Name");
		dftDataTx.addColumn("Request");
		dftDataTx.addColumn("Packet Data");
		jPanel4.add(jScrollPane5);
		jScrollPane5.setBounds(10, 20, 400, 90);

		getContentPane().add(jPanel4);
		jPanel4.setBounds(250, 360, 420, 120);

		txtNme.setEditable(false);
		txtPort.setEditable(false);

		setSize(700, 530);
		setResizable(false);
		setVisible(true);
	}// </editor-fold>

	// GEN-END:initComponents

	private void btnDownActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String selpath = receive.allPaths.get(receive.allPaths.firstKey());
		Vector<String> path = action.getPath(selpath);
		Vector<String> retpath = action.getPath(selpath);
		action.sendData(mrx, path, retpath, txtSearch.getText());
	}

	private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (jtaNeigh.getText().equals(""))
			JOptionPane.showMessageDialog(null,
					"Servers are not there.");
		else {
			Vector<String> path = new Vector<String>();
			path.add(source);
			action.routing(mrx, path, txtSearch.getText());
		}
	}

	private void btnMRWBActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		dis = txtDistance.getText();
		if (dis.equals(""))
			JOptionPane.showMessageDialog(null, "Enter the Tasks.");
		else {
			mrx = new MulticastRx(this);
			new MulticastTx(source, dis, port);
			btnMRWB.setEnabled(false);
		}
	}

	private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		browse();
	}

	private void browse() {
		// TODO Auto-generated method stub
		JFileChooser chooser = new JFileChooser("Database");
		chooser.setMultiSelectionEnabled(true);
		chooser.setAcceptAllFileFilterUsed(false);
		chooser.setFileFilter(new FileFilter() {
			public boolean accept(File f) {
				return f.getName().toLowerCase().endsWith(".txt")
						|| f.getName().toLowerCase().endsWith(".java")
						|| f.getName().toLowerCase().endsWith(".htm")
						|| f.getName().toLowerCase().endsWith(".html")
						|| f.getName().toLowerCase().endsWith(".xml")
						|| f.isDirectory();
			}

			public String getDescription() {
				return "Files";
			}
		});
		int check = chooser.showOpenDialog(this);
		try {
			if (check == JFileChooser.APPROVE_OPTION) {

				File[] path = chooser.getSelectedFiles();
				for (int i = 0; i < path.length; i++) {
					dftFiles.addRow(new Object[] { path[i].getName() });
					allFiles.add(path[i].getName());
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public Vector<String> allFiles;

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		try {
			String inf = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
			UIManager.setLookAndFeel(inf);
		} catch (Exception e) {
			e.printStackTrace();
		}
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Server().setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnAdd;
	private javax.swing.JButton btnDown;
	private javax.swing.JButton btnMRWB;
	private javax.swing.JButton btnSearch;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JScrollPane jScrollPane5;
	public javax.swing.JTextArea jtaNeigh;
	public javax.swing.JTextArea jtaSarchDet;
	private javax.swing.JTable tblAData;
	private javax.swing.JTable tblDataTx;
	private javax.swing.JTable tblDown;
	private javax.swing.JTextField txtDistance;
	private javax.swing.JTextField txtNme;
	private javax.swing.JTextField txtPort;
	public javax.swing.JTextField txtSearch;
	DefaultTableModel dftFiles;
	public DefaultTableModel dftDataTx;
	public DefaultTableModel dftDown;
	// End of variables declaration//GEN-END:variables

}